org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.07.28

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,)
neo_version=21.1.118
neo_version_range=[21.0.0-beta,)
loader_version_range=[4,)

mod_id=soul_forge
mod_name=Soul Forge
mod_license=GPL-3.0
mod_version=1.0.0
mod_group_id=com.github.x3r
mod_authors=x3r, reavez
mod_description=

geckolib_version=4.7.3
geckolib_version_range=[4.7,)

sbl_version=1.16.7
sbl_version_range=[1.16,)

